# Generated by Django 3.2.4 on 2021-07-07 20:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('user_middle_name', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('user_last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('user_mothers_last_name', models.CharField(blank=True, max_length=20, verbose_name="Mother's Last Name")),
                ('user_bio', models.TextField(max_length=1000, verbose_name='Bio')),
                ('user_job_title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('user_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('user_phone', models.CharField(blank=True, default='x', max_length=20, verbose_name='Mobile')),
                ('user_to_display', models.BooleanField(default=None, null=True, unique=True, verbose_name='Show user cv')),
            ],
        ),
        migrations.CreateModel(
            name='MyWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=20, verbose_name='Company Name')),
                ('deg_or_pos', models.CharField(max_length=40, verbose_name='Job Position')),
                ('company_fow', models.CharField(max_length=60, verbose_name='Field of Work')),
                ('company_url', models.URLField(blank=True, verbose_name='Company Website')),
                ('inst_logo', models.URLField(blank=True, verbose_name='Company Logo URL')),
                ('location_city', models.CharField(max_length=25, verbose_name='City')),
                ('location_country', models.CharField(max_length=25, verbose_name='Country')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('current', models.BooleanField(default=False, verbose_name='Current Job')),
                ('job_description', models.TextField(max_length=1000, verbose_name='Job Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyTemplateURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_icon', models.URLField(blank=True, max_length=300, verbose_name='Brand icon')),
                ('my_resume', models.URLField(blank=True, max_length=300, verbose_name='Resume URL')),
                ('profile_picture', models.URLField(blank=True, max_length=300, verbose_name='profile picture')),
                ('background_picture', models.URLField(blank=True, max_length=300, verbose_name='Background image')),
                ('whatsapp_widget', models.CharField(blank=True, max_length=300, verbose_name='Whatsapp Widget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MySocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=20, verbose_name='Social Name (Ref only)')),
                ('social_desc', models.CharField(max_length=30, verbose_name='Social name to display')),
                ('social_url', models.URLField(blank=True, verbose_name='Social URL')),
                ('social_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
                ('social_is_contact', models.BooleanField(default=False, verbose_name='Contact info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30, verbose_name='Skill')),
                ('skill_description', models.CharField(blank=True, max_length=60, verbose_name='Skill Description')),
                ('skill_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
                ('skill_is_language', models.BooleanField(blank=True, default=False, verbose_name='Language Skill')),
                ('skill_is_tech', models.BooleanField(blank=True, default=False, verbose_name='Tech Skill')),
                ('skill_is_other', models.BooleanField(blank=True, default=False, verbose_name='Other Skill')),
                ('skill_is_soft', models.BooleanField(blank=True, default=False, verbose_name='Soft Skill')),
                ('skill_is_hobby', models.BooleanField(blank=True, default=False, verbose_name='Hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, verbose_name='Project Name')),
                ('project_desc', models.TextField(max_length=1000, verbose_name='Description')),
                ('project_code_url', models.URLField(blank=True, verbose_name='Link to project')),
                ('project_live_url', models.URLField(blank=True, verbose_name='Link to live page')),
                ('project_photo', models.URLField(blank=True, verbose_name='Preview photo link')),
                ('project_techs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=35), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg_or_pos', models.CharField(max_length=60, verbose_name='Degree')),
                ('inst_name', models.CharField(max_length=60, verbose_name='Univeristy / Institution')),
                ('inst_logo', models.URLField(blank=True, verbose_name='Uni/Inst logo URL')),
                ('edu_url', models.URLField(blank=True, verbose_name='Uni/Inst Website')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('current', models.BooleanField(default=False, verbose_name='Currently Studying')),
                ('activities', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=30, verbose_name='Certificate Name')),
                ('certificate_desc', models.CharField(blank=True, max_length=50, verbose_name='Certificate Description')),
                ('certificate_institution', models.CharField(blank=True, max_length=50, verbose_name='Institution')),
                ('certificate_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
    ]
