# Generated by Django 3.2.4 on 2021-06-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('user_middle_name', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('user_last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('user_mothers_last_name', models.CharField(blank=True, max_length=20, verbose_name="Mother's Last Name")),
                ('user_bio', models.TextField(max_length=1000, verbose_name='Bio')),
                ('user_job_title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('user_email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='MyWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='Company Name')),
                ('employee_position', models.CharField(max_length=40, verbose_name='Job Position')),
                ('company_fow', models.CharField(max_length=60, verbose_name='Field of Work')),
                ('company_url', models.URLField(blank=True, verbose_name='Company Website')),
                ('company_logo', models.URLField(blank=True, verbose_name='Company Logo URL')),
                ('location_city', models.CharField(max_length=25, verbose_name='City')),
                ('location_country', models.CharField(max_length=25, verbose_name='Country')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('current', models.BooleanField(default=False, verbose_name='Current Job')),
                ('job_description', models.TextField(max_length=1000, verbose_name='Job Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MySocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=20, verbose_name='Social Name (Ref only)')),
                ('social_desc', models.CharField(max_length=30, verbose_name='Social name to display')),
                ('social_url', models.URLField(blank=True, verbose_name='Social URL')),
                ('social_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30, verbose_name='Skill')),
                ('skill_description', models.CharField(blank=True, max_length=60, verbose_name='Skill Description')),
                ('skill_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
                ('skill_is_language', models.BooleanField(blank=True, default=False, verbose_name='Language Skill')),
                ('skill_is_tech', models.BooleanField(blank=True, default=False, verbose_name='Tech Skill')),
                ('skill_is_other', models.BooleanField(blank=True, default=False, verbose_name='Other Skill')),
                ('skill_is_soft', models.BooleanField(blank=True, default=False, verbose_name='Soft Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_degree', models.CharField(max_length=60, verbose_name='Degree')),
                ('edu_institution', models.CharField(max_length=60, verbose_name='Univeristy / Institution')),
                ('edu_logo', models.URLField(blank=True, verbose_name='Uni/Inst logo URL')),
                ('edu_url', models.URLField(blank=True, verbose_name='Uni/Inst Website')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('current', models.BooleanField(default=False, verbose_name='Currently Studying')),
                ('activities', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=30, verbose_name='Certificate Name')),
                ('certificate_desc', models.CharField(blank=True, max_length=50, verbose_name='Certificate Description')),
                ('certificate_institution', models.CharField(blank=True, max_length=50, verbose_name='Institution')),
                ('certificate_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
    ]
