# Generated by Django 3.2.4 on 2021-06-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskills',
            name='skill_is_hobby',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hobby'),
        ),
    ]
