# Generated by Django 3.2.4 on 2021-06-30 15:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_myskills_skill_is_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProjec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, verbose_name='Social Name (Ref only)')),
                ('project_desc', models.TextField(max_length=1000, verbose_name='Social name to display')),
                ('project_url', models.URLField(blank=True, verbose_name='Social URL')),
                ('project_photo', models.URLField(blank=True, verbose_name='Social URL')),
                ('project_techs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.myuser')),
            ],
        ),
    ]
