# Generated by Django 3.2.4 on 2021-06-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_myuser_user_mothers_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_bio',
            field=models.TextField(max_length=1000, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_job_title',
            field=models.CharField(max_length=50, verbose_name='Job Title'),
        ),
    ]
