# Generated by Django 3.2.4 on 2021-06-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210627_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycertificates',
            name='certificate_icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='mycertificates',
            name='certificate_institution',
            field=models.CharField(blank=True, max_length=50, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='myeducation',
            name='activities',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myeducation',
            name='edu_logo',
            field=models.URLField(blank=True, verbose_name='Uni/Inst logo URL'),
        ),
        migrations.AlterField(
            model_name='myeducation',
            name='edu_url',
            field=models.URLField(blank=True, verbose_name='Uni/Inst Website'),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='skill_description',
            field=models.CharField(blank=True, max_length=60, verbose_name='Skill Description'),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='skill_icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='mysocial',
            name='social_icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='mysocial',
            name='social_url',
            field=models.URLField(blank=True, verbose_name='Social URL'),
        ),
        migrations.AlterField(
            model_name='myworkexperience',
            name='company_logo',
            field=models.URLField(blank=True, verbose_name='Company Logo URL'),
        ),
        migrations.AlterField(
            model_name='myworkexperience',
            name='company_url',
            field=models.URLField(blank=True, verbose_name='Company Website'),
        ),
    ]
