# Generated by Django 3.2.4 on 2021-06-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_myprojec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProjec',
            new_name='MyProjects',
        ),
    ]
