# Generated by Django 3.2.4 on 2021-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210627_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycertificates',
            name='certificate_desc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Certificate Description'),
        ),
    ]
