# Generated by Django 3.2.4 on 2021-06-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_mycertificates_certificate_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskills',
            name='skill_is_language',
            field=models.BooleanField(blank=True, default=False, verbose_name='Language Skill'),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_is_other',
            field=models.BooleanField(blank=True, default=False, verbose_name='Other Skill'),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_is_soft',
            field=models.BooleanField(blank=True, default=False, verbose_name='Soft Skill'),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_is_tech',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tech Skill'),
        ),
    ]
