# Generated by Django 3.2.4 on 2021-06-30 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210630_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='project_techs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
    ]
