# Generated by Django 3.2.4 on 2021-06-30 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_myprojects_project_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='project_name',
            field=models.CharField(max_length=20, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='project_techs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=35), size=None),
        ),
    ]
