# Generated by Django 3.2.4 on 2021-06-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210630_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myeducation',
            old_name='edu_degree',
            new_name='deg_or_pos',
        ),
        migrations.RenameField(
            model_name='myeducation',
            old_name='edu_logo',
            new_name='inst_logo',
        ),
        migrations.RenameField(
            model_name='myeducation',
            old_name='edu_institution',
            new_name='inst_name',
        ),
        migrations.RenameField(
            model_name='myworkexperience',
            old_name='employee_position',
            new_name='deg_or_pos',
        ),
        migrations.RenameField(
            model_name='myworkexperience',
            old_name='company_logo',
            new_name='inst_logo',
        ),
        migrations.RenameField(
            model_name='myworkexperience',
            old_name='company_name',
            new_name='inst_name',
        ),
    ]
