# Generated by Django 3.2.4 on 2021-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20210701_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysocial',
            name='social_is_contact',
            field=models.BooleanField(default=False, verbose_name='Contact info'),
        ),
    ]
