# Generated by Django 3.2.4 on 2021-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_mysocial_social_is_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_phone',
            field=models.CharField(blank=True, default='x', max_length=20, verbose_name='Mobile'),
        ),
    ]
