# Generated by Django 3.2.4 on 2021-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_myuser_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_to_display',
            field=models.BooleanField(default=None, null=True, unique=True, verbose_name='Show user cv'),
        ),
    ]
